import { calculateCryptoPortfolio, type CryptoHoldingInput, type CryptoMarket } from './cryptoPortfolio.ts';
const assert = (condition: boolean, message: string) => { if (!condition) throw new Error(message) };
const holding = (patch: Partial<CryptoHoldingInput> = {}): CryptoHoldingInput => ({ id: '1', provider_asset_id: 'bitcoin', symbol: 'BTC', name: 'Bitcoin', image_url: null, quantity: '0.00001234', average_buy_price: null, average_buy_currency: null, ...patch });
const market = (id: string, price: number, change = 10): CryptoMarket => ({ id, current_price: price, market_cap: null, price_change_percentage_24h: change, last_updated: null });

Deno.test('preserves high precision quantity and calculates value', () => { const result = calculateCryptoPortfolio([holding()], new Map([['bitcoin', market('bitcoin', 100000)]]), 'USD', 'now', false); assert(result.positions[0].quantity === 0.00001234, 'quantity'); assert(Math.abs(result.summary.portfolioValue - 1.234) < 1e-9, 'value') });
Deno.test('calculates weights for a batch portfolio', () => { const result = calculateCryptoPortfolio([holding({ quantity: 1 }), holding({ id: '2', provider_asset_id: 'ethereum', symbol: 'ETH', name: 'Ethereum', quantity: 2 })], new Map([['bitcoin', market('bitcoin', 100)], ['ethereum', market('ethereum', 50)]]), 'USD', 'now', false); assert(result.positions.every((position) => position.weight === 50), 'weights') });
Deno.test('calculates PnL only with positive average price', () => { const withAverage = calculateCryptoPortfolio([holding({ quantity: 2, average_buy_price: 80, average_buy_currency: 'USD' })], new Map([['bitcoin', market('bitcoin', 100)]]), 'USD', 'now', false); assert(withAverage.positions[0].profitLoss === 40 && withAverage.positions[0].profitLossPercent === 25, 'pnl'); const without = calculateCryptoPortfolio([holding()], new Map([['bitcoin', market('bitcoin', 100)]]), 'USD', 'now', false); assert(without.positions[0].profitLoss === null, 'missing average') });
Deno.test('portfolio 24h change is value-weighted, not average percent', () => { const result = calculateCryptoPortfolio([holding({ quantity: 10 }), holding({ id: '2', provider_asset_id: 'ethereum', symbol: 'ETH', name: 'Ethereum', quantity: 1 })], new Map([['bitcoin', market('bitcoin', 110, 10)], ['ethereum', market('ethereum', 50, -50)]]), 'USD', 'now', false); assert(Math.abs(result.summary.portfolioChange24h - 50) < 1e-9, 'weighted change') });
Deno.test('missing price stays explicit and does not erase other values', () => { const result = calculateCryptoPortfolio([holding(), holding({ id: '2', provider_asset_id: 'unknown' })], new Map([['bitcoin', market('bitcoin', 10)]]), 'USD', 'now', true); assert(result.summary.missingPriceCount === 1 && result.summary.stale, 'missing/stale') });
