export const categoryIconNames = [
  'Utensils',
  'Coffee',
  'Train',
  'Car',
  'Home',
  'HeartPulse',
  'Sparkles',
  'Repeat',
  'ShoppingBag',
  'Gift',
  'PlaneTakeoff',
  'ChartColumn',
  'Landmark',
  'BadgeDollarSign',
  'CircleEllipsis',
  'BriefcaseBusiness',
  'Laptop',
  'BookOpen',
] as const

export const categoryIconLabels: Record<(typeof categoryIconNames)[number], string> = {
  Utensils: 'Еда',
  Coffee: 'Кофе',
  Train: 'Транспорт',
  Car: 'Авто',
  Home: 'Дом',
  HeartPulse: 'Здоровье',
  Sparkles: 'Развлечения',
  Repeat: 'Повтор',
  ShoppingBag: 'Покупки',
  Gift: 'Подарок',
  PlaneTakeoff: 'Путешествие',
  ChartColumn: 'Инвестиции',
  Landmark: 'Бизнес',
  BadgeDollarSign: 'Продажа',
  CircleEllipsis: 'Другое',
  BriefcaseBusiness: 'Работа',
  Laptop: 'Ноутбук',
  BookOpen: 'Книга',
}
