export const categoryIconNames = [
  'Utensils',
  'Train',
  'Home',
  'HeartPulse',
  'Sparkles',
  'Repeat',
  'ShoppingBag',
  'Car',
  'CircleEllipsis',
  'BriefcaseBusiness',
  'Laptop',
  'Plane',
  'Coffee',
  'BookOpen',
  'Dumbbell',
] as const

export const categoryIconLabels: Record<(typeof categoryIconNames)[number], string> = {
  Utensils: 'Еда',
  Train: 'Транспорт',
  Home: 'Дом',
  HeartPulse: 'Здоровье',
  Sparkles: 'Развлечения',
  Repeat: 'Повтор',
  ShoppingBag: 'Покупки',
  Car: 'Авто',
  CircleEllipsis: 'Другое',
  BriefcaseBusiness: 'Работа',
  Laptop: 'Ноутбук',
  Plane: 'Самолет',
  Coffee: 'Кофе',
  BookOpen: 'Книга',
  Dumbbell: 'Спорт',
}
